### ISSUE TITLE
Investigate removal of GEM files

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#103]
Since removal of the Ruby-based SASS libraries, it's not clear to me if we need these any longer.

**Comment by roblarsen** [comment]
![image](https://cloud.githubusercontent.com/assets/361421/6414099/0a69b614-be63-11e4-92db-bac70337b71a.png)

**Comment by roblarsen** [comment]
(Some day, I will stop following updates on this repo. Today is not that day.)

**Comment by rcherny** [comment]
@roblarsen you really don't have to :)

**Comment by rcherny** [comment]
Believe this was done. Sadly I don't know which commit and it's not important so I'm going to be lazy and not look it up.

**Comment by roblarsen** [comment]
Ah, Jem and the Holograms...
