### ISSUE TITLE
Modify Gruntfile 'watch' task to watch the handlebars templates and everything needed

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#104]
Effectively only a content change will re-run assemble at the moment. We need it to re-run when the layouts, templates, partials, and other content changes, or the dev workflow is stuck by having to re-run assemble which goes against the whole point of a watch task.

**Comment by rcherny** [comment]
This may be done. Need to double-check.

**Comment by ericdouglaspratt** [comment]
The watch task only checks 'content/en/**.*'. I'll modify it to watch everything else that can affect the HTML.

**Comment by ericdouglaspratt** [comment]
Has been fixed. Grunt "watch" command should now be listening to all appropriate content folders.
