### ISSUE TITLE
The links to the Authors' twitter pages are broken

### ISSUE THREAD

**Issue by jaredwilli** [isobar-idev/code-standards#110]
Hey, I just noticed that the Twitter links in the Authors part of the doc are all broken. The URLs are all like http://twitter.com/#%21/username.

Need to remove the /#%21 part so it's just http://twitter.com/username.

**Comment by rcherny** [comment]
@jaredwilli please note we're no longer really working on updates to the master branch. we have a rewrite in master.next in progress. thanks tho!
