### ISSUE TITLE
Sidebar menu doesn't work on iPhone with scrollTo enabled

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#139]
The commit that added back (#124) the add to top seems to have broken the responsive nav. I'll fix.

**Comment by rcherny** [comment]
http://www.shdon.com/blog/2013/06/07/why-your-click-events-don-t-work-on-mobile-safari

Event delegation broke it.

Making other tweaks too.

**Comment by roblarsen** [comment]
Fastclick, yo

**Comment by rcherny** [comment]
You're right. It's crazy choppy right now ...

**Comment by rcherny** [comment]
Will hopefully add it tomorrow, good call. 

https://github.com/ftlabs/fastclick

**Comment by roblarsen** [comment]
Fastclick or pointer events with https://github.com/jquery/PEP are the awesomeness.

**Comment by rcherny** [comment]
We can make it fancier. But it works better at this point. PEP is **very** slick, and I do like the scrolling options there which would enhance the side navigation menu, but I need to focus on content. If anyone wants to issue a pull request with an enhancement, please feel free.
