### ISSUE TITLE
Idea: Pull most links out to separate section

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#49]
I'm concerned about link rot and things like that. Also, in terms of resources, they are fluid and a dime a dozen (sometimes).

Effectively I'm thinking that we start to get really careful about what we allow as a hard coded link in the standards doc going forward.

I'm thinking that perhaps the things like the Appendix or possibly even references or sources for each section in the document be pulled out into pages similar to this:

https://github.com/isobar-idev/code-standards/wiki/Useful-Links-and-Resources

Not in one page, and probably Markdown pages in an actual Repo, since Github Wikis, as I understand it, are source control challenged.

Just a thought. We might have a "useful resources" link at the end of each section, or something along those lines.

My reasoning is that links come and go, as do valuable resources, but the Standards Doc content should be a little more vetted, a little more persistant, even though it will continue (hopefully, but let's be realistic) to be a living document.

I'd want the resources to be even more fluid and easy to change. Also, it will drive traffic to our Github.

Thoughts? Opinions? Feelings? Reactions? Good? Bad? Indifferent?

**Comment by dforesman** [comment]
I worry about linking directly to specs, as so often the _spec_ and the _actual browser implementations_ differ. Not to mention that w3c spec pages are horrific to read.

I've investigated some options that could help us deal with link rot problem, logged in https://github.com/isobar-idev/code-standards/issues/123

Regardless of whether we pull links out into a separate section, or leave them inline, an automated link-checker could be useful.

**Comment by rcherny** [comment]
I suspect we won't be doing this. Ended up with links in there anyways, as long as we can curate the better going forwards...
