### ISSUE TITLE
Fork badge in corner of page is buggy

### ISSUE THREAD

**Issue by jaredwilli** [isobar-idev/code-standards#6]
## When viewed in Opera on web:

As you scroll down the page when in *Opera*, the badge in the corner flickers, and is buggy-like.

## When viewing via iPad2:

The page looks and works fine on *iPad* when the screen orientation changes from vertical to horizontal, Except the positioning of the Fork badge. It remains in place when it is set to whichever view is the most narrow. It should be stuck in the corner no matter which way you hold the device.

**Comment by rcherny** [comment]
New branch uses new version. So this is a non-issue. Will review as part of final QA pre-launch.
