### ISSUE TITLE
LEGACY FILE CLEAN UP: Remove old and unused files from repo

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#60]
There are a lot of files no longer needed for the new build. Also no longer used in the doc at all. There's other tickets, this is the parent. They include:

* Add static.html and index.html to .gitignore, remove index.php #58 
* remove old CSS - 6b1d217-raiso.css #62
* remove old CSS - handheld.css #62
* remove old Font Files - #63
* remove /inc folder - #64
* remove old JS (too much junk) - #65

**Comment by rcherny** [comment]
This just needs to be reviewed. We should verify what's been done and what hasn't, and remove, without hesitation, anything old.

**Comment by ericdouglaspratt** [comment]
JS cleanup is handled in #97. So all we need to look at here are SCSS, CSS, and images.

**Comment by rcherny** [comment]
I think this is done except for the ./src/images folder. I'm going to create another ticket for that.
