### ISSUE TITLE
Object Literal/Singleton link is dead

### ISSUE THREAD

**Issue by brandly** [isobar-idev/code-standards#77]
A little below [here](http://isobar-idev.github.io/code-standards/#_javascript_libraries), you'll see [Object Literal/Singleton](http://kaijaeger.com/articles/the-singleton-design-pattern-in-javascript.html).

**Comment by rcherny** [comment]
Thanks for the link fix. We're actually going to close this and I don't believe the link in question is even used any longer once we switch branches.

Always appreciate the help, however.
