### ISSUE TITLE
Need responsive syntax highlighting solution for code samples

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#85]
When #30 is done we need a responsive syntax highlighter. Preferably:

- one that supports line numbers
- one that supports "standards based output" (like http://prismjs.com/) 
- one that can work with our new markdown processor via Assemble
- one that is RESPONSIVE (did I mention that?)

**Comment by rcherny** [comment]
We need to check with Lydia on this one. She had a working version but at the least we need to have this work better then what we had.

So:
- check with Lydia
- if it's problematic
- check with Sarah she had some ideas

**Comment by rcherny** [comment]
Need to start from scratch here. There were ... issues ...

**Comment by roblarsen** [comment]
>Need to start from scratch here. There were ... issues ...

Zombies? Robots?

**Comment by ericdouglaspratt** [comment]
Code complete, pull request merged.
