### ISSUE TITLE
Remove ruby dependencies if possible

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#92]
Discussed going to use something like: 

https://www.npmjs.com/package/grunt-libsass

So we wouldn't need to use the Ruby set up and it'd be "just node". But not sure which features are being used.

**Comment by rcherny** [comment]
@quoo can we remove the Gemfiles as well, then?

**Comment by ericdouglaspratt** [comment]
grunt-libsass has been replaced by grunt-sass, thanks to rob! were there any other things you guys had in mind for this task, or can we close?

**Comment by rcherny** [comment]
I think that was all there was. I'll close it. Thanks guys!
