### ISSUE TITLE
Remove legacy Spanish Content

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#95]
After the changes to swap out the old content with the new content we have a disconnect, as the old Spanish has yet to be updated.

These changes:
https://github.com/isobar-idev/code-standards/pull/93
https://github.com/isobar-idev/code-standards/pull/94

are the English changes. We'll need to remove the old Spanish content, change the build to include translations for the Spanish content under /content

**Comment by rcherny** [comment]
We'll probably need to get in touch with someone on the translation as the old content is settled more.

**Comment by ericdouglaspratt** [comment]
For this ticket, (1) convert Spanish folder structure to the new structure matching the English setup, (2) have the Spanish assemble task in the Gruntfile but commented out, (3) have dummy blank files in the Spanish folder.

**Comment by ericdouglaspratt** [comment]
Fixed by fdbc6c2d15ac3b0f98f526553d540f015ee7abba

**Comment by ericdouglaspratt** [comment]
Code complete, pull request merged.
