### ISSUE TITLE
Move client-files to _assets folder

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#96]
These folders:

- `css/`
- `img/`
- `js/`
- `scss/`

... are intended to live under the new `_assets` folder. The structure in there is up for debate, but typically we should have a `_assets/css/src` and in lieu of a `/target` folder we would put the output in the root of that folder (e.g. `_assets/css/foo.css`).

With a build process for client assets it's a good practice to have the static assets consolidated in a centralized location in case a CDN, subdomain, or other variation on the http server is used. It also simply makes for a cleaner file system that has less "visual noise".

**Comment by rcherny** [comment]
This will need to have the `gruntfile` updated and the build tested, of course.

**Comment by ben-caplan** [comment]
@rcherny: I have this just about wrapped up. I was not sure though in your example of folder structure how the CSS root vs src folders would play out. Do we have any CSS src? Isn't that our SCSS?

**Comment by rcherny** [comment]
@ben-caplan I'm about to submit a pull request with this done. I did change things a little bit with the `generated` folders you had. Basically I've got a new `src` folder at the top level and the "generated" files now go into `_assets`. 

Hoping this sits OK with everyone. It's a pretty big restructuring, but the file system looks so much cleaner (IMHO)...

**Comment by rcherny** [comment]
Wow I'm sorry I didn't see your questions at the time. We have another set of tickets about the dupes and old files, and they're to be cleaned up. I've got a couple pull requests on those in progress now.

Here I go getting wrapped up in infrastructure again instead of the content though ...

**Comment by ben-caplan** [comment]
No worries. Sounds totally fine. Please feel free to make any and all
changes!

--
Benjamin Reif-Caplan
Web Developer
IAmCaplan.com
617.764.5079 (Office)
617.285.1602 (Cell)
@Ben_Caplan <https://twitter.com/Ben_Caplan>
ben@iamcaplan.com
