### ISSUE TITLE
Revise JS for new branch

### ISSUE THREAD

**Issue by rcherny** [isobar-idev/code-standards#97]
Update jQuery or drop it all together, fix the navigation (if applicable with the new responsive layout), remove the old files in /js, use a version of `modernizr` that only has what we need, and so on.

We'll also need a concat job and such.

**Comment by rcherny** [comment]
Realistically, this will need to wait a little bit until the new highlighter, the new responsive layout, and so forth. Let's make our JS nice on this, it shouldn't do more than it needs to do.

**Comment by roblarsen** [comment]
I say make the JS gross and super complicated.

**Comment by rcherny** [comment]
You mean, leave it the way it is?

**Comment by rcherny** [comment]
Remove old stuff, update jQuery, remove unused plugins etc.

**Comment by ericdouglaspratt** [comment]
jQuery has been updated, navigation works with slight performance improvement, old files in /js have been removed, concat job has been added.

Remaining tasks: (1) use a version of modernizr that has only what we need, (2) add a Grunt task that doesn't minify the JS for dev purposes.

**Comment by ben-caplan** [comment]
@ericdouglaspratt: for the Grunt task, do you mind clarifying what you would like? I imagine that we do want to minify the generated code, no? Or is our preference to have simple concatenation without any minification?

**Comment by ericdouglaspratt** [comment]
@ben-caplan yes, the default Grunt tasks should still do production-style minification and concatenation. But we'll need separate Grunt tasks (including a watch task) that don't do the minification (and if it's easy, don't do the concatenation either) for development purposes and easy debugging.

**Comment by ericdouglaspratt** [comment]
Talked with @ben-caplan, there's a good deal of complexity involved here (e.g. generating files with different names, changing references to the script files in the HTML somehow) so we'll call that out of scope for this particular task.

Remaining work for this task is just to use a version of Modernizr that has only what we need, or remove it entirely if we're not using it at all.

**Comment by ben-caplan** [comment]
Pending pull request review, merge and QA this ticket is good to close (and of course noting Eric's comment above regarding the Grunt task)
